# Generated by Django 2.2 on 2019-06-18 02:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_empleos'),
        ('mainUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmprExpe', models.CharField(max_length=150, verbose_name='Empresa')),
                ('TeleEmpr', models.CharField(max_length=30, verbose_name='Telefono de contacto de la empresa')),
                ('JefeExpe', models.CharField(max_length=30, verbose_name='Persona de contacto de la empresa')),
                ('FechInic', models.DateTimeField(default=0, verbose_name='Fecha de Inicio')),
                ('FechFin', models.DateTimeField(default=0, verbose_name='Fecha de Terminación')),
                ('FuncionE', ckeditor.fields.RichTextField(verbose_name='Funciones desempeñadas')),
                ('LogrExpe', ckeditor.fields.RichTextField(verbose_name='Logros Alcanzados')),
                ('SopoExpe', models.FileField(default='', upload_to='soportes/laboral', verbose_name='Certificado Laboral')),
                ('EstaExpt', models.CharField(default='Activo', max_length=30, verbose_name='Estado de experiencia')),
                ('CargExpe', models.ForeignKey(limit_choices_to={'Es cargo': 'SI'}, on_delete=django.db.models.deletion.CASCADE, to='parametros.Empleos', verbose_name='Cargo Ocupado')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencia Laboral',
            },
        ),
    ]
