# Generated by Django 2.2 on 2019-06-18 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0003_auto_20190617_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='CargExpe',
            field=models.ForeignKey(limit_choices_to={'NombCarg': 'SI'}, on_delete=django.db.models.deletion.CASCADE, to='parametros.Empleos', verbose_name='Cargo Ocupado'),
        ),
    ]
