# Generated by Django 2.2 on 2019-06-18 03:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_empleos'),
        ('mainUser', '0004_auto_20190617_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombHabil', models.CharField(default='Activo', max_length=100, verbose_name='Habilidad')),
                ('NiveHabil', models.CharField(default='Activo', max_length=20, verbose_name='Nivel de Habilidad: ')),
            ],
            options={
                'verbose_name': 'Habilidades',
                'verbose_name_plural': 'Habilidades y Competencias',
            },
        ),
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechLogr', models.DateTimeField(default=0, verbose_name='Fecha de culminación de logro')),
                ('NombLogr', models.CharField(default='Activo', max_length=100, verbose_name='Logro o Distinción')),
                ('DescLogr', ckeditor.fields.RichTextField(verbose_name='Descripción o caracteristicas del logro')),
                ('NombTiLo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoLogr', verbose_name='Tipo de Logro')),
            ],
            options={
                'verbose_name': 'Logros',
                'verbose_name_plural': 'Logros Obtenidos',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instituto', models.CharField(default='Activo', max_length=30, verbose_name='Inistitución o Academia')),
                ('TituloEst', models.CharField(max_length=250, verbose_name='Institución o Academia')),
                ('SoporteEs', models.FileField(default='0', upload_to='soportes/eduacion', verbose_name='Soporte de educación')),
                ('FechGrado', models.DateTimeField(default='Activo', max_length=30, verbose_name='Estado de educación')),
                ('TipoEstu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoEstu', verbose_name='Tipo de Educción')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Estudios Registrados',
            },
        ),
    ]
