# Generated by Django 2.2 on 2019-06-22 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0005_educacion_habilidades_logros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='TipoEstu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoEstu', verbose_name='Tipo de educación'),
        ),
    ]
