# Generated by Django 2.2 on 2019-06-22 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0006_auto_20190621_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='idTipoDocu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoDocu', verbose_name='Tipo de documento'),
        ),
    ]
