# Generated by Django 2.2 on 2019-06-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0010_auto_20190622_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='RegiUsua',
            field=models.DateField(default='0', verbose_name='Registrado el: '),
        ),
    ]
