# Generated by Django 2.2 on 2019-06-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0011_auto_20190622_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='FechFin',
            field=models.DateField(default=0, verbose_name='Fecha de Terminación'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='FechInic',
            field=models.DateField(default=0, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='logros',
            name='FechLogr',
            field=models.DateField(default=0, verbose_name='Fecha de culminación de logro'),
        ),
    ]
