# Generated by Django 2.2.2 on 2019-06-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0014_auto_20190622_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
