# Generated by Django 2.2.2 on 2019-06-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0015_delete_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educacion',
            name='TipoEstu',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='CargExpe',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
        migrations.RemoveField(
            model_name='logros',
            name='NombTiLo',
        ),
        migrations.DeleteModel(
            name='Educacion',
        ),
        migrations.DeleteModel(
            name='Experiencia',
        ),
        migrations.DeleteModel(
            name='Logros',
        ),
    ]
