# Generated by Django 2.2.2 on 2019-06-22 23:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0002_empleos'),
        ('mainUser', '0016_auto_20190622_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombHabil', models.CharField(default='', max_length=100, verbose_name='Habilidad')),
                ('NiveHabil', models.CharField(default='', max_length=20, verbose_name='Nivel de Habilidad: ')),
            ],
            options={
                'verbose_name': 'Habilidades',
                'verbose_name_plural': 'Habilidades y Competencias',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuario', models.CharField(default='', max_length=50, verbose_name='No. Identificación')),
                ('Nombre', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('Apellido', models.CharField(default='', max_length=200, verbose_name='Apellido')),
                ('Correo', models.CharField(default='@', max_length=250, verbose_name='Correo')),
                ('ImagUsua', models.ImageField(upload_to='perfiles/img', verbose_name='Foto de Perfil')),
                ('PerfilPro', ckeditor.fields.RichTextField(default='Candidato...', verbose_name='Perfil Profesional')),
                ('GeneUsua', models.CharField(default='', max_length=1, verbose_name='Género')),
                ('TeleUsua', models.CharField(default='', max_length=20, verbose_name='Teléfono')),
                ('CeluUsua', models.CharField(default='', max_length=20, verbose_name='Celular')),
                ('DireUsua', models.CharField(default='', max_length=50, verbose_name='Dirección Postal')),
                ('RegiUsua', models.DateField(verbose_name='Registrado el: ')),
                ('idEstaCivil', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.EstaCivil', verbose_name='Estado civil')),
                ('idEtnias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.Etnia', verbose_name='Etnias')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoDocu', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechLogr', models.DateField(verbose_name='Fecha de culminación de logro')),
                ('NombLogr', models.CharField(max_length=100, verbose_name='Logro o Distinción')),
                ('DescLogr', ckeditor.fields.RichTextField(verbose_name='Descripción o caracteristicas del logro')),
                ('NombTiLo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoLogr', verbose_name='Tipo de Logro')),
            ],
            options={
                'verbose_name': 'Logros',
                'verbose_name_plural': 'Logros Obtenidos',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmprExpe', models.CharField(max_length=150, verbose_name='Empresa')),
                ('TeleEmpr', models.CharField(max_length=30, verbose_name='Telefono de contacto de la empresa')),
                ('JefeExpe', models.CharField(max_length=30, verbose_name='Persona de contacto de la empresa')),
                ('FechInic', models.DateField(default=0, verbose_name='Fecha de Inicio')),
                ('FechFin', models.DateField(default=0, verbose_name='Fecha de Terminación')),
                ('FuncionE', ckeditor.fields.RichTextField(verbose_name='Funciones desempeñadas')),
                ('LogrExpe', ckeditor.fields.RichTextField(verbose_name='Logros Alcanzados')),
                ('SopoExpe', models.FileField(default='', upload_to='soportes/laboral', verbose_name='Certificado Laboral')),
                ('CargExpe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Empleos', verbose_name='Cargo Ocupado')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencia Laboral',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instituto', models.CharField(max_length=30, verbose_name='Inistitución o Academia')),
                ('TituloEst', models.CharField(max_length=250, verbose_name='Institución o Academia')),
                ('FechGrado', models.DateField(verbose_name='Fecha de graduación')),
                ('SoporteEs', models.FileField(default='0', upload_to='soportes/eduacion', verbose_name='Soporte de educación')),
                ('TipoEstu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoEstu', verbose_name='Tipo de educación')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Estudios Registrados',
            },
        ),
    ]
