# Generated by Django 2.2.2 on 2019-06-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0017_educacion_experiencia_habilidades_logros_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='EstaEstu',
            field=models.CharField(default='Activo', max_length=30, verbose_name='Estado de educación'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='EstaExpt',
            field=models.CharField(default='Activo', max_length=30, verbose_name='Estado de experiencia'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='EstaUsua',
            field=models.CharField(default='Activo', max_length=50, verbose_name='Estado'),
        ),
    ]
