# Generated by Django 2.2.2 on 2019-06-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0019_remove_usuarios_regiusua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='idEstaCivil',
        ),
    ]
