# Generated by Django 2.2.2 on 2019-06-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0022_auto_20190624_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='IdUsuario',
            new_name='id',
        ),
    ]
