# Generated by Django 2.2.2 on 2019-06-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0024_auto_20190624_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='IdUsuario',
            new_name='id',
        ),
    ]
