# Generated by Django 2.2.2 on 2019-06-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0025_auto_20190624_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id',
            new_name='IdUsuario',
        ),
    ]
