# Generated by Django 2.2.2 on 2019-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0026_auto_20190624_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='EstaUsua',
            field=models.BooleanField(default='Activo', verbose_name='Estado'),
        ),
    ]
