# Generated by Django 2.2.2 on 2019-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0027_auto_20190624_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='FechGrado',
            field=models.DateField(null=True, verbose_name='Fecha de graduación'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='TituloEst',
            field=models.CharField(max_length=250, verbose_name='Titulo de estudio'),
        ),
    ]
