# Generated by Django 2.2.2 on 2019-06-25 16:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_empleos'),
        ('mainUser', '0028_auto_20190624_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educacion',
            name='TipoEstu',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='CargExpe',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
        migrations.RemoveField(
            model_name='logros',
            name='NombTiLo',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='CargExpe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.Empleos', verbose_name='Cargo Ocupado'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='DescLogr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Descripción o caracteristicas del logro'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='EmprExpe',
            field=models.CharField(max_length=150, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='FechLogr',
            field=models.DateField(null=True, verbose_name='Fecha de culminación de logro'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='FuncionE',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Funciones desempeñadas'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Instituto',
            field=models.CharField(max_length=30, null=True, verbose_name='Inistitución o Academia'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='LogrExpe',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Logros Alcanzados'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='NiveHabil',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Nivel de Habilidad: '),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='NombHabil',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Habilidad'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='NombLogr',
            field=models.CharField(max_length=100, null=True, verbose_name='Logro o Distinción'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='NombTiLo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoLogr', verbose_name='Tipo de Logro'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='TipoEstu',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoEstu', verbose_name='Tipo de educación'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='TituloEst',
            field=models.CharField(max_length=250, null=True, verbose_name='Titulo de estudio'),
        ),
        migrations.DeleteModel(
            name='Educacion',
        ),
        migrations.DeleteModel(
            name='Experiencia',
        ),
        migrations.DeleteModel(
            name='Logros',
        ),
    ]
