# Generated by Django 2.2.2 on 2019-06-25 18:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0029_auto_20190625_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='FuncionE',
            field=ckeditor.fields.RichTextField(max_length=250, null=True, verbose_name='Funciones desempeñadas'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='LogrExpe',
            field=ckeditor.fields.RichTextField(max_length=250, null=True, verbose_name='Logros Alcanzados'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='PerfilPro',
            field=ckeditor.fields.RichTextField(default='Candidato...', max_length=250, verbose_name='Perfil Profesional'),
        ),
    ]
