# Generated by Django 2.2.2 on 2019-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0030_auto_20190625_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='DescLogr',
            field=models.CharField(max_length=250, null=True, verbose_name='Descripción o caracteristicas del logro'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='FuncionE',
            field=models.CharField(max_length=250, null=True, verbose_name='Funciones desempeñadas'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='LogrExpe',
            field=models.CharField(max_length=250, null=True, verbose_name='Logros Alcanzados'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='PerfilPro',
            field=models.CharField(default='Candidato...', max_length=250, verbose_name='Perfil Profesional'),
        ),
    ]
