# Generated by Django 2.2.2 on 2019-06-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0031_auto_20190625_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Correo',
            field=models.CharField(default='', max_length=250, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='NiveHabil',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Nivel de Habilidad '),
        ),
    ]
