# Generated by Django 2.2 on 2019-06-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tipom',
            field=models.CharField(choices=[('Queja', 'Queja'), ('Felicitación', 'Felicitación'), ('Solicitud', 'Solicitud'), ('Reclamo', 'Reclamo'), ('Petición', 'Petición')], default='Petición', max_length=50, verbose_name='Categoría'),
        ),
    ]
