# Generated by Django 2.2 on 2019-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190621_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tipom',
            field=models.CharField(choices=[('Queja', 'Queja'), ('Solicitud', 'Solicitud'), ('Petición', 'Petición'), ('Reclamo', 'Reclamo'), ('Felicitación', 'Felicitación')], default='Petición', max_length=50, verbose_name='Categoría'),
        ),
    ]
