# Generated by Django 2.2 on 2019-06-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190622_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tipom',
            field=models.CharField(choices=[('Queja', 'Queja'), ('Petición', 'Petición'), ('Solicitud', 'Solicitud'), ('Reclamo', 'Reclamo'), ('Felicitación', 'Felicitación')], default='Petición', max_length=50, verbose_name='Categoría'),
        ),
    ]
