# Generated by Django 2.2.2 on 2019-06-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190622_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tipom',
            field=models.CharField(choices=[('Reclamo', 'Reclamo'), ('Petición', 'Petición'), ('Queja', 'Queja'), ('Solicitud', 'Solicitud'), ('Felicitación', 'Felicitación')], default='Petición', max_length=50, verbose_name='Categoría'),
        ),
    ]
