# Generated by Django 2.2.2 on 2019-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190624_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tipom',
            field=models.CharField(choices=[('Reclamo', 'Reclamo'), ('Petición', 'Petición'), ('Felicitación', 'Felicitación'), ('Queja', 'Queja'), ('Solicitud', 'Solicitud')], default='Petición', max_length=50, verbose_name='Categoría'),
        ),
    ]
