# Generated by Django 2.2.2 on 2019-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190624_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tipom',
            field=models.CharField(choices=[('Solicitud', 'Solicitud'), ('Petición', 'Petición'), ('Reclamo', 'Reclamo'), ('Felicitación', 'Felicitación'), ('Queja', 'Queja')], default='Petición', max_length=50, verbose_name='Categoría'),
        ),
    ]
