# Generated by Django 2.2.2 on 2019-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190624_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tipom',
            field=models.CharField(choices=[('Solicitud', 'Solicitud'), ('Petición', 'Petición'), ('Queja', 'Queja'), ('Felicitación', 'Felicitación'), ('Reclamo', 'Reclamo')], default='Petición', max_length=50, verbose_name='Categoría'),
        ),
    ]
