# Generated by Django 2.2.2 on 2019-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20190625_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tipom',
            field=models.CharField(choices=[('Solicitud', 'Solicitud'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Felicitación', 'Felicitación'), ('Petición', 'Petición')], default='Petición', max_length=50, verbose_name='Categoría'),
        ),
    ]
