# Generated by Django 2.2.2 on 2019-06-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190625_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tipom',
            field=models.CharField(choices=[('Queja', 'Queja'), ('Solicitud', 'Solicitud'), ('Felicitación', 'Felicitación'), ('Reclamo', 'Reclamo'), ('Petición', 'Petición')], default='Petición', max_length=50, verbose_name='Categoría'),
        ),
    ]
