# Generated by Django 2.2 on 2019-06-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomiCarg', models.CharField(default='', max_length=1, verbose_name='Dominio')),
                ('ClasCarg', models.CharField(default='', max_length=2, verbose_name='Clase')),
                ('OrdeCarg', models.CharField(default='', max_length=3, verbose_name='Orden')),
                ('GeneCarg', models.CharField(default='', max_length=4, verbose_name='Genero')),
                ('NombCarg', models.CharField(default='', max_length=250, verbose_name='Nombre de Cargo')),
                ('EsCargo', models.CharField(default='', max_length=20, verbose_name='Es Cargo')),
            ],
            options={
                'verbose_name': 'Cargos',
                'verbose_name_plural': 'Empleos y Cargos',
            },
        ),
    ]
